### ISSUE TITLE
Node-Red Password and Username

### ISSUE THREAD

**Issue by wstephan** [myStrom/node-red-contrib-mystrom#2]
Hi
Congratulations for this Node. I secured my Node-Red with Password and Username. Like that, it isn't possible to connect to this node. Please provide optional username and password field.

Best regards 
Steve

**Comment by Hadjimina** [comment]
Hi,

Actually I tried it with a secured Node-RED instance without a problem. What you mean by "...secured Node-RED with username and password" is simply that in order for you to acces the Node-RED webui you need a password and username to login, correct?

Additional you you share a screenshot or a description of what you are trying to achieve, so that I can get a better idea of where the problem might be.

Cheers

**Comment by wstephan** [comment]
Hi Philipp

yes, i have Username and Password to Access Node Red. Of course, this make only sense, when i use also https. Could that be the problem? Or is a self signed certificate a problem?

I can send Configuration to my Button from the node:

{"success":"true","response":"{    "single": "post:\/\/192.168.xx.yy:1880\/buttons?mac=60:01:94:XX:YY:WW&action=0",    "double": "post:\/\/192.168..xx.yy:1880\/buttons?mac=60:01:94:XX:YY:WW&action=1",    "long": "post:\/\/192.168..xx.yy:1880\/buttons?mac=60:01:94::XX:YY:WW&action=2",    "touch": "post:\/\/192.168.xx.yy:1880\/buttons?mac=60:01:94:XX:YY:WW&action=3",    "generic": ""}"}

But when i press the Button, nothing is received by the node.....

Best regards

Steve

**Comment by Hadjimina** [comment]
Hi Steve,

Ah I see. That's pretty problematic because the buttons sadly do not support SSL requests.

A workaround would be to use a Rasperry Pi or similar, setup a separate node-red instance without using SSL , connect the buttons to that instance and execute the SSL requests from this separate node-red instance whenever the button is triggered. 

Sorry that there is not more that I can do

Cheers
